apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes
images:
  - name: ghcr.io/dotbrains/bureau
    digest: sha256:56feb68ff1eea2ece0a6f0f7e8eaf522ad958021d0672fe6fe74abb69a22889c
configMapGenerator:
  - name: bureau-config
    namespace: bureau
    behavior: replace
    literals:
      - BUREAU_PUBLIC_URL=https://office.k8s.test
patches:
  - target:
      kind: Ingress
      name: bureau
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: office.k8s.test
      - op: replace
        path: /spec/rules/1/host
        value: "*.office.k8s.test"
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
        value: arn:aws:acm:REGION:ACCOUNT:certificate/REPLACE_WITH_CERTIFICATE_ID
