import type { AppState } from "./store.tsx";
import { readSidePanels } from "./store-side-panels.ts";

export const initialState: AppState = {
  agents: [],
  logs: new Map(),
  focusedAgentId: null,
  connected: false,
  hasReceivedInitialState: false,
  isMobile: typeof window !== "undefined" ? window.innerWidth < 768 : false,
  mobileViewMode: typeof localStorage !== "undefined" && localStorage.getItem("bureau-mobile-view") === "list" ? "list" : "office",
  needsAttention: new Set(),
  sessionsList: new Map(),
  soundTrigger: { seq: 0, roomId: null, agentId: null, agentName: null },
  drafts: new Map(),
  recentCwds: [],
  slashCommands: new Map(),
  stateChangedAt: new Map(),
  office: { prompt: null, envFile: null },
  rooms: [],
  allRooms: [],
  users: new Map(),
  sessionContext: null,
  activeSessions: [],
  activeSessionsLoaded: false,
  invitesList: [],
  invitesLoaded: false,
  presences: [],
  totalOnlineUsers: 0,
  tasks: [],
  tasksLoaded: false,
  currentRoom: 0,
  cronjobs: [],
  cronjobsLoaded: false,
  cronjobsPrompt: null,
  cronjobRunsByJob: new Map(),
  cronjobRunsLoaded: false,
  ccPlugins: null,
  updateAvailable: false,
  updateCurrent: { sha: "", message: "", date: "" },
  updateLatest: { sha: "", message: "", date: "" },
  sidePanels: readSidePanels(),
  killedAgents: [],
};
