import type { AppState } from "./store.tsx";
import { storageGetItem } from "./browser-storage.ts";
import { readSidePanels } from "./store-side-panels.ts";

export const initialState: AppState = {
  agents: [],
  logs: new Map(),
  logsReplay: null,
  focusedAgentId: null,
  connected: false,
  hasReceivedInitialState: false,
  hydrationEpoch: 0,
  isMobile: typeof window !== "undefined" ? window.innerWidth < 768 : false,
  mobileViewMode: storageGetItem("bureau-mobile-view") === "list" ? "list" : "office",
  needsAttention: new Set(),
  sessionsList: new Map(),
  soundTrigger: { seq: 0, roomId: null, agentId: null, agentName: null },
  drafts: new Map(),
  recentCwds: [],
  slashCommands: new Map(),
  stateChangedAt: new Map(),
  office: { prompt: null, envFile: null, previewAllowHosts: [], experimental: { browserPanel: false }, receptionistAgentId: null },
  rooms: [],
  allRooms: [],
  users: new Map(),
  sessionContext: null,
  activeSessions: [],
  activeSessionsLoaded: false,
  invitesList: [],
  invitesLoaded: false,
  presences: [],
  totalOnlineUsers: 0,
  tasks: [],
  tasksLoaded: false,
  apps: [],
  appsLoaded: false,
  appsRevision: 0,
  currentRoom: 0,
  lobbyOpen: false,
  cronjobs: [],
  cronjobsLoaded: false,
  cronjobsPrompt: null,
  cronjobRunsByJob: new Map(),
  cronjobRunsLoaded: false,
  ccPlugins: null,
  updateStatus: {
    mode: "commit",
    updateAvailable: false,
    current: { release: null, sha: "" },
    latest: null,
    releaseStanding: "unknown",
    mainAhead: 0,
  },
  sidePanels: readSidePanels(),
  killedAgents: [],
};
